### ISSUE TITLE
Titulo errado na wiki

### ISSUE THREAD

**Issue by Nixsm** [betweenthelines/privacidade-negada#1]
Higiene e bons hábitos -> Celulares/Tables/etc
O titulo desta parte da wiki esta escrito Tables ao invés de Tablets.
Não consigo fazer um pull-request pois esta na wiki.

Link de referência:
https://github.com/betweenthelines/privacidade-negada/wiki/Higiene-e-bons-h%C3%A1bitos#celularestablesetc

**Comment by benmezger** [comment]
Thanks. Closing as it's fixed.
